### ISSUE TITLE
Wire frames 

### ISSUE THREAD

**Issue by vanderpatrick** [vanderpatrick/HackAMusic#10]

**Comment by halfpintutopia** [comment]
To be discussed:

Make a wireframe with:

- index
- game
- instructions

Are the following needed for a game:

- footer
- header

**Comment by MaxRan92** [comment]
Wireframes created and pushed.
Waiting for team's feedbacks.

**Comment by halfpintutopia** [comment]
Wireframes in the project under docs/images
