### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vanderpatrick** [vanderpatrick/HackAMusic#7]
Read me File should be documented as much as possible, we all know how annoying read me's are

**Comment by halfpintutopia** [comment]
TODO:

- [ ] Finish README.md file 
  - [ ] Add the setup @MaxRan92  @IvetteMcDermott , I am not sure what to add to this part?
  - [ ] Add the deployed link
  - [ ] Add LinkedIn profile links
  - [ ] Add assets  @MaxRan92  @IvetteMcDermott , does that also mean to list the CSS files?
